module.exports = {
  MOSTRAR_PRODUCTOS: "MOSTRAR_PRODUCTOS",
  MOSTRAR_PRODUCTO: "MOSTRAR_PRODUCTO",
  AGREGAR_PRODUCTO: "AGREGAR_PRODUCTO",
  EDITAR_PRODUCTO: "EDITAR_PRODUCTO",
  ELIMINAR_PRODUCTO: "ELIMINAR_PRODUCTO",
  REALIZAR_PEDIDO: "REALIZAR_PEDIDO",
  PALABRA_BUSCADOR: "PALABRA_BUSCADOR",
  OBTENER_ORDENES: "OBTENER_ORDENES",
  OBTENER_ORDENES_TODAS: "OBTENER_ORDENES_TODAS"
};
